services:
  target-server:
    build: . # Сборка из локального Dockerfile
    container_name: vpn_target
    networks:
      vpn_net:
        ipv4_address: 10.5.0.5
    # Команда запуска сервиса при старте контейнера (опционально)
    command: bash -c "service ssh start && service apache2 start && tail -f /dev/null"

  attacker-client:
    build: .
    container_name: vpn_client
    networks:
      vpn_net:
        ipv4_address: 10.5.0.6
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    privileged: true
    volumes:
      - .:/data
    command: tail -f /dev/null

  traffic-sniffer:
    build: .
    container_name: vpn_sniffer
    network_mode: "service:attacker-client"
    privileged: true
    volumes:
      - ./data:/data   # <-- ИЗМЕНЕНИЕ ЗДЕСЬ
    command: tail -f /dev/null
networks:
  vpn_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24
